### PR TITLE
Adapt 'format' to Pelican 4.0

### LINKED ISSUE #196: Pelican traceback with RSS Feeds generation
Hi
If I do set RSS feeds generation for anything other than ALL:

~~~
# CATEGORY_FEED_ATOM = 'feeds/{slug}.atom.xml'
# CATEGORY_FEED_RSS = 'feeds/{slug}.rss'
# TRANSLATION_FEED_ATOM = 'feeds/{lang}.atom.xml'
# TRANSLATION_FEED_RSS = 'feeds/{lang}.rss'
# AUTHOR_FEED_ATOM = 'feeds/{slug}.atom.xml'
# AUTHOR_FEED_RSS = 'feeds/{slug}.rss'
# TAG_FEED_ATOM = 'feeds/tag_{slug}.atom.xml'
# TAG_FEED_RSS = 'feeds/tag_{slug}.rss'
~~~

I do get a pelican traceback:

~~~
-> Writing /home/iranzo/DEVEL/private/www/output/feeds/all.atom.xml
-> Writing /home/iranzo/DEVEL/private/www/output/feeds/all.rss
CRITICAL: TypeError: not all arguments converted during string formatting
Traceback (most recent call last):
  File "/usr/bin/pelican", line 11, in <module>
    load_entry_point('pelican==3.7.1', 'console_scripts', 'pelican')()
  File "/usr/lib/python3.7/site-packages/pelican/__init__.py", line 487, in main
    pelican.run()
  File "/usr/lib/python3.7/site-packages/pelican/__init__.py", line 179, in run
    p.generate_output(writer)
  File "/usr/lib/python3.7/site-packages/pelican/generators.py", line 599, in generate_output
    self.generate_feeds(writer)
  File "/usr/lib/python3.7/site-packages/pelican/generators.py", line 312, in generate_feeds
    % cat.slug, feed_title=cat.name)
TypeError: not all arguments converted during string formatting

~~~

### PR DESCRIPTION
**Pull request by iranzo**
Closes #196

### CODE REVIEW

**Comment by iranzo** [comment]
Added the slug part ffor 4.0 approach

**Comment by talha131** [comment]
@iranzo will this change work for Pelican 3.* as well? or just 4.0?

We decided to release a 2.0 version against Pelican 3.0. Version 2.1 is supposed to be the release with 4.0 support. The idea was to close open PR and push 2.0 quickly out of the doors.

Let me know how this commit affects user on Pelican 3.*. Also let me know your thoughts on the subject. Do you agree with a 2.1 release for Pelican 4.0 support or you think we should add 4.0 support to 2.0 milestone.

**Comment by iranzo** [comment]
As per discussion on #196  it does affect and it's either one or the other

**Comment by talha131** [comment]
@iranzo No need to close and reopen PR. I dropped to cmd and merged the PR.

Close via b2397e8f9d2095952f98bcd83685ef33ec6e43fd

**Pull request closed without merging**
