### PR TITLE
Add ability to hide article with certain metadata value

### PR DESCRIPTION
**Pull request by azzamsa**
Now user can hide an article with metadata:

```
Visible: False
```

User can use this article as a PAGE. e.g for photo gallery, list of talks, contributions, projects, etc.

Upstream pelican had [Status: hidden](https://github.com/getpelican/pelican/pull/389/files), but it's introduced some errors, so I came up with my own approach.

### CODE REVIEW

**Comment by iranzo** [comment]
Why category = False, shouldn't the article visible be enough?

What's the reason behind that?

Thanks for explaining it to me!

**Comment by azzamsa** [comment]
> Why category = False, shouldn't the article visible be enough?

Absolutely, This is my own skill limitation. I can't figure it out how to get `article.visible` when the template loop for `categories`. e.g [here](https://github.com/Pelican-Elegant/elegant/blob/3820a3bec651211815f988e00e2f5ff01a2da473/templates/categories.html#L43)

So, my dirty quick hack is to add `category: False`. I believe you have more beautiful approach for this.

**Comment by azzamsa** [comment]
**KNOWN BUG**: I have known bug I can't solve [here](https://github.com/Pelican-Elegant/elegant/blob/3820a3bec651211815f988e00e2f5ff01a2da473/templates/archives.html#L48). When I have only one article in certain year, the year still appear even the article is hidden.

**Comment by iranzo** [comment]
In the modified archives.html, lines 48 and 62 will render the same, if the endif were not before, so probably the if can be simplified

About the bug you mention in prior comment, I would say it's because the article you pushed there is in a new category which is not used by other articles, so it list the category even if later we filter out the articles.

**Comment by azzamsa** [comment]
If I changed to :

``` django
<div class="row-fluid">
    <div class="span10 offset2">
        <div class="blog-archives">
            {% for article in dates %}
            {% set year = article.date.strftime('%Y') %}
            {% if loop.first %}
            <h2 id="{{year }}"><a href="#{{year}}">{{ year }}</a></h2>
            {% else %}
            {% set prevyear = loop.previtem.date.strftime('%Y') %}
            {%if prevyear != year %}
            <h2 id="{{year }}"><a href="#{{year}}">{{ year }}</a></h2>
            {% endif %}
            {% endif %}

            {% if article.category != 'False' %}
            {% if loop.last %}
            <article itemscope class="last-entry-of-year">
                {% else %}
                {% set next_year = loop.nextitem.date.strftime('%Y') %}

                {% if next_year != year %}
                <article itemscope class="last-entry-of-year">
                    {% else %}
                    <article itemscope>
                        {% endif %}
                        {% endif %}

                        <a href="{{ SITEURL }}/{{ article.url }}">{{ article.title }} {%if article.subtitle %} <small> {{ article.subtitle }} </small> {% endif %} </a>
                        <time itemprop="dateCreated" datetime="{{ article.date.isoformat() }}">{{ article.locale_date }}</time>
                        {% endif %}
                    </article>
                    {% endfor %}
        </div>
    </div>
</div>
```

All hidden pages comes up.

**Comment by iranzo** [comment]
This is what I get when using peru to sync plugins, get your blog content and use the elegant version indicated:

image


Is that a valid starting point for debugging?

Thanks!
Pablo

**Comment by iranzo** [comment]
image

Is that better?

**Comment by azzamsa** [comment]
My bad, I am forgot to change `Category: MYPAGE` to `Category: FALSE`.

Fixed https://github.com/azzamsa/azzamsa.github.io/commit/9af8369bdfb4d550032e6019c38a94f1d56fefb8

**Comment by iranzo** [comment]
No worries, I now see that when Category is Mypage it shows the category with empty article list as you indicated

**Comment by iranzo** [comment]
Please, apply this patch over your templates and validate


[fichero.zip](https://github.com/Pelican-Elegant/elegant/files/2755379/fichero.zip)

**Comment by iranzo** [comment]
BTW, remove category=False as should not be needed if I didn't missed something

**Comment by azzamsa** [comment]
Removing `Category: FALSE` now works.

But two bugs I mentioned earlier still exist.

**Comment by iranzo** [comment]
Sorry, which ones are missing right now?

Thanks!
Pablo

**Comment by azzamsa** [comment]
> Sorry, which ones are missing right now?

1) If year only contain one article
2) If year contain one article and article.visible = False

**Comment by iranzo** [comment]
With the uploaded set:

- Articles with Visible: False are hidden
- 1 Article  in one year, looks ok:

image


What is missing is to filter out the only article in a year if it's set to Visible:False

**Comment by iranzo** [comment]
image

**Comment by iranzo** [comment]
And with:

image


image

**Comment by azzamsa** [comment]
> And with:

Have you tried the year to be the end year. e.g 2016 ?

**Comment by azzamsa** [comment]
You rock @iranzo. I learn a lot from you. Code and workflow. A lot. Thank you.

**Comment by iranzo** [comment]
@azzamsa can you confirm it now works as you expected?

**Comment by azzamsa** [comment]
> @azzamsa can you confirm it now works as you expected?

Sorry, we have differrent timezone :)

I've tried, I don't know. it didn't work for me

1) I use the latest revision from your push.

I added the word 'ala' to indicate that my 'make html' use the right theme and revision



2) the problem still occur

**Comment by iranzo** [comment]
This is the tarball of the environment I used for validation, can you check with it?

[azzamsa.github.io.zip](https://github.com/Pelican-Elegant/elegant/files/2758339/azzamsa.github.io.zip)

**Comment by azzamsa** [comment]
Downloaded, tried, no luck.




No different in code, just some untracked files.

**Comment by azzamsa** [comment]
Sure. I just copy the 'elegant' dir. I don't copy all the articles. Now:

1) run `make html` to untouched zip : worked great




2) remove all '*-testalone' : works great

2022-01-14-testalone.md
2021-01-14-testalone.md
2020-01-14-testalone.md
2019-01-14-testalone.md





3) remove '2018-04-07-mengatur-berkas-referensi.markdown' : I don't know.

Previously '2018-04-07-mengatur-berkas-referensi.markdown' in 2018

**Comment by azzamsa** [comment]
Strange:

1) when I remove all article in 2018, just add testalone-2018



2) when I remove test-alone-2018



I will learn how pelican parse the date, it's in filename (jekyll-like) or just in metadata. I will refactor all the filename to match the metadata

**Comment by iranzo** [comment]
ok, same result here, when following your steps.

I've tried restoring original elegant theme with the only following files remaining:

2017-09-14-how-i-came-to-know-gnu-slash-linux.markdown
2017-11-05-read-number-to-list-in-common-lisp.markdown
2018-11-26-kumpulan-panduan-emacs-bahasa-indonesia.markdown


And seems to work fine, so at least is something that works fine with Elegant theme by default (or looks like)

**Comment by iranzo** [comment]
Testing putting elegant theme back from the modified branch, now still shows the same format:

image



I would say to try to reproduce trying elegant original theme from  master branch to see if it's an issue with theme and not with this patch.

@talha131 any idea on how to debug? generated html file?

**Comment by azzamsa** [comment]
I try different step to find the bug.

1) reformat all the filename. without any date in filename

2) copy all my articles : worked fine



3) delete two (left one article) in 2018 : the bug reproduced

**Comment by azzamsa** [comment]
> I would say to try to reproduce trying elegant original theme from master branch to see if it's an issue with theme and not with this patch.

Yes, I believe at some level it comes from this patch. 

Really mysterious bug I've ever face :)

**Comment by iranzo** [comment]
@azzamsa now that you've reproduced, can you attach the generated archives.html page when you see the bug so that we can check what could be missing there?

**Comment by azzamsa** [comment]
Turn out the only `<article itemscope>` missing ` <article itemscope class="last-entry-of-year">`

```diff
$ colordiff archives-worked.html archives-bug.html
81,84d80
<                                     <article itemscope class="last-entry-of-year">
<                                 <a href="http://localhost:8000/mengatur-berkas-referensi.html">Mengatur Berkas&nbsp;Referensi  </a>
<                                 <time itemprop="dateCreated" datetime="2018-04-07T16:24:01+07:00">Apr 07, 2018</time>
<                                 </article>
```

**Comment by iranzo** [comment]
Ok, the issue is related with the hidden article, being the last in the loop, so the loop doesn't print that sentence as it's not the last article, but it's the one that it's visible

**Comment by azzamsa** [comment]
Tried to solve it but still didn't work :)

yes, we have to make sure that article with visible = False didn't get into the loop. The strange thing is: we have filtered them using if before loop.last. But when I check loop.nextitem the hidden article printed out.

**Comment by iranzo** [comment]
Try my latest upload of templates

**Comment by azzamsa** [comment]
Tried your hack `{% for article in articles if article.visible != 'False' %}` : worked



I have two article in 2018, one of them hidden. It works with your hack. So strange, we never do something like `for article in articles if article.visible != 'False'` in regular python script. 

Is this maybe comes from jinja indentation ?

**Comment by iranzo** [comment]
That comes from Jinja template, in python you can do something similar with blocks:

https://github.com/citellusorg/citellus/blob/master/citellusclient/shell.py#L279-L281


So, can you recheck that all features now work as expected so that we can move on with review from my colleagues?

Thanks,
Pablo

**Comment by azzamsa** [comment]
> That comes from Jinja template, in python you can do something similar with blocks

I see, but with nested if we had previously, hidden articles should be filtered already. But, this case is new knowledge for me, in case something similar happen.

> So, can you recheck that all features now work as expected so that we can move on with review from my colleagues?

yes, it works like a charm

**Comment by iranzo** [comment]
@talha131 confirmed to work with curent code

**Comment by iranzo** [comment]
I've updated your comment to remove the 'category: false'  in the PR description

**Comment by talha131** [comment]
@azzamsa before we merge this PR, can you please explain what purpose does hiding an article serve? Pelican already has support for `draft`, which hides the article from all the lists. Doesn't `draft` and your PR do the same thing?

**Comment by azzamsa** [comment]
Why would we need `Visible:False` :

### Status: draft

Pelican already had [Status:draft](https://docs.getpelican.com/en/3.6./content.html#publishing-drafts) which will not listed those page on the index page nor on any category or tag page. It's clear that the goal of this feature is for reviewing or for article that not ready to be seen by public.

### Status: hidden

Pelican also had [Status: hidden](https://github.com/getpelican/pelican/pull/389/files), but it's introduced some errors if we use it for articles. The goal of this feature is to have 'hidden' pages for custom error (or any internal pages.)


### Our case

1) we wan to create *separate* article to list our [talks](http://cs.azzamsa.com/talks), [writings](http://cs.azzamsa.com/writing), [contributions](https://cs.azzamsa.com/projects-contributed), [photo gallery](https://cs.azzamsa.com/photo-gallery-lugos-man-1) and etc. Of course we want those page in 'publishing' mode, not in 'draft' mode. And we don't want those page to appear in categories, tags, related articles, neighbors, etc.

2) I tried `status: hidden` for this purpose, and it introduced some error if I use for this kind of purpose.

**Comment by talha131** [comment]
Thanks a lot @azzamsa. I really appreciate you taking the time to explain.

>     1. e wan to create _separate_ article to list our [talks](http://cs.azzamsa.com/talks), [writings](http://cs.azzamsa.com/writing), [contributions](https://cs.azzamsa.com/projects-contributed), [photo gallery](https://cs.azzamsa.com/photo-gallery-lugos-man-1) and etc.

Wouldn't using a Page instead of article be more appropriate here?

**Comment by azzamsa** [comment]
> Wouldn't using a Page instead of article be more appropriate here?

Pelican treat page and article differently. If we use pages the will automatically appears in navbars. Also using page is not appropriate for putting something like photo galleries (at least for me).

I want to have simple way to put my images, (not things like picasa or google images)

**Comment by talha131** [comment]
Sorry, I closed this PR by mistake.

**Comment by iranzo** [comment]
@azzamsa I've rebased on top of current master, can you validate it still works for you?

Thanks,
Pablo

**Comment by azzamsa** [comment]
image

tried https://github.com/azzamsa/elegant/commit/a8982b99651744ce996f279409461df6902d32c5 : Worked.

**Comment by iranzo** [comment]
Thanks!

**Comment by iranzo** [comment]
@talha131 next candidate to work on? ;-)

**Comment by talha131** [comment]
>  If we use pages the will automatically appears in navbars. 

If a page is hidden then it does not appear in the navbar.

> Also using page is not appropriate for putting something like photo galleries (at least for me).

Perhaps. But if you used a hidden page for photo gallery, you would not have needed this patch at all.

----

I think the main issue is Pelican only has two types of content

1. Posts
2. Pages

It expects users to use Page for special posts like talks, resume etc.

A more robust solution is to let user define its own content type and its taxonomy. [GoHugo](https://gohugo.io/content-management/types/) is very flexible in this regard. It lets user define new content type.

This is related to #460.

Say I have a list of presentations. I don't want them to appear in the archives or categories. How do I do that?

Or I want to publish my favorite poems. They cannot be categorized using the usual tags or categories. How do I publish them and keep them out of Archives page? Also let user filter them using poets, language, poets DOB etc?

Or what if I want to use different template or stylesheet for my presentations or poems collection?

This can be solved by either adding support for user content type to Pelican core or creating a plugin that lets you do it.

I think this patch and #460 are a step towards adding new content types to Pelican. But a better and more maintainable solution is to enhance Pelican core or adding a new plugin.

In distant future, I plan to look into plugin system more intently and see if it is even possible via plugins.

**Comment by azzamsa** [comment]
> Perhaps. But if you used a hidden page for photo gallery, you would not have needed this patch at all.

Yeah, I think so. but when I tried hidden page feature as mentioned above https://github.com/Pelican-Elegant/elegant/pull/270#issue-244090159, it didn't work for me. so I come out with my own solution.

I don't know if the error come from my wrong config / pelican it self.

---

I don't expect so much for this patch to be merged upstream (elegant), if this turns out not to be clean approach. But for me I will stay with this until I have free time to deal with hidden page errors (not anytime soon).

**Comment by talha131** [comment]
> Yeah, I think so. but when I tried hidden page feature as mentioned above #270 (comment), it didn't work for me. so I come out with my own solution.

Can you please tell me about your photo gallery setup? I would try to reproduce it at my end.

----

Pelican has a template pages feature.

https://docs.getpelican.com/en/stable/settings.html?highlight=TEMPLATE_PAGES%20#template-pages

Perhaps it can be used for one time special pages. Say we add a page for talks, and one for resume. Then users can use those special pages without having to resort to this patch.

**Comment by azzamsa** [comment]
> Can you please tell me about your photo gallery setup? I would try to reproduce it at my end.

My goals is so simple:

1. I want to have "hidden page". The page that didn't appear anywhere in other pages, except I link them explicitly. (e.g in my [recent post](https://cs.azzamsa.com/), in my [archieve](https://cs.azzamsa.com/archives), and in my categories and tags). Plus it didn't appear in reading recommendation link (next article suggestion)

2. I don't want them to appear in navbar

Here some of them:
https://cs.azzamsa.com/talks
https://cs.azzamsa.com/writing
https://cs.azzamsa.com/photo-fs-anywhere

Here is my blog source: https://github.com/azzamsa/cs/. I use my own version of elegant, with my incomplete patch (but fixed by Iranzo above).

**Comment by azzamsa** [comment]
Hi @talha131 @iranzo 

Sorry for the late reply. I will tell short story here.

I want only simple thing:

1) hide the the "article" that's not suitable to be shown in "keep reading", "archive", "recent post". The example would be my `about.markdown`, `writings.markdown`, `talks.markdown`, `photos-***.markdown`

Those "article" only contains list of my contributions, talks, writings, and list of photos of certain events.

---

before I use octopress and searching for new platform for my static blog for some reasons. I just have limited time for this migration, so I do everything in hurry. Then I am looking a way to satisfy specification above (1). I found this commit at that time:

1. [Add support for `status: hidden` in pages #389](https://github.com/getpelican/pelican/pull/389/files)

And tried right away adding `Status: hidden` in my metadata. But it didn't work after multiple trial. So I decide right away to implement the same thing that I did in octopress.

So, I come up with this PR that we deal it today.

----

After times, now I have a "stable" time after exams and interviews. So this morning, I tried to re-research this issue. I pulled the newest revision from `next` branch and start looking is anything break in my blog. All fine except this specification (1). I try again to use `status:hidden` getting error message and paste that into google (I skip this step before, I just ignore the message without searching what really happened), then I find this issue:

1. [Hidden pages handled incorrectly #1929 ](https://github.com/getpelican/pelican/issues/1929)

Turn out pelican has it's own term for "article", "pages", etc. This is what make me think that even the [PR was merged](https://github.com/getpelican/pelican/pull/389/files), how come it didn't work. I just realize that it's for "pages" not for "article". (I remember found some people use `status:draft` before, but i think "draft" and "hidden" is not the same think, so i just skip it)

After some search, I try `status:draft` it served me well. All the "articles" that I wanna hide is gone from archive, recent post, next read, etc. **so I think we can close this PR for now. I can use `status:draft` safely for now.**. 

---

**What I'm afraid is that pelican or elegant will put any attribute stating that this article is draft** (like what readthedocs did if we visit old version of the docs not the latest). So that I think why people still asking `pelican` team to implement them:

1) [:status: hidden for things other than pages. #519](https://github.com/getpelican/pelican/issues/519)
2) [Hidden status for articles](https://github.com/getpelican/pelican/issues/1965)

---

Thank you so much for patiently handling this PR @talha131 and helping so much resource @iranzo .

**Comment by azzamsa** [comment]
The changes in `status:draft` article is separated from normal article (put into /drafts directory and accessed via /draft/article-title). So if you want to override the normal article with the draft. The trick is to add these two lines:


``` python
# Defaults
DEFAULT_CATEGORY = 'Miscellaneous'
USE_FOLDER_AS_CATEGORY = False
ARTICLE_URL = u'{slug}'
PAGE_URL = u'{slug}'
DRAFT_URL = u'{slug}' <----
DRAFT_SAVE_AS = u'{slug}.html' <----
```

**Comment by talha131** [comment]
Thanks for the detailed responses. 

Is there anything that needs to be done here? Can we close this PR now?

**Comment by azzamsa** [comment]
> Thanks for the detailed responses.
> 
> Is there anything that needs to be done here? Can we close this PR now?

Yes, I just need you to know before closing this. Just that.

the current elegant & pelican behavior are able to preserve `status:draft` for my need. If it's changed. Maybe I need different hack.

Thank you for your patience.

**Pull request closed without merging**
