### PR TITLE
Remove Hound

### PR DESCRIPTION
**Pull request by iranzo**
Remove Hound configuration from repository

## Prerequisites

- [X] My Pull Request is filled against the `next` branch
- [-] I have updated the [CHANGELOG](https://github.com/Pelican-Elegant/elegant/blob/next/CHANGELOG.md)

## Recommended Steps

- [ ] My patch adds a new feature, therefore I have also added a help article about it
- [ ] My patch changes Elegant behavior, therefore I have updated the help article to reflect this change
- [x] My commits are [signed](https://help.github.com/en/articles/signing-commits)

### CODE REVIEW

**Comment by talha131** [comment]
I didn't close this PR. No idea what happened. I can't reopen it now. reopen button is disabled.

**Comment by iranzo** [comment]
Done, my 'next' was not at latest... it makes it a bit hard to work with master and next when doing PR's :-)

/me is more used to 'master' for latest and 'releases' for the released version

**Comment by talha131** [comment]
Thank you @iranzo.

You missed to edit the commit message :)

**Comment by talha131** [comment]
We need to adhere to commit conventions in order to make automated release work.

**Comment by iranzo** [comment]
Done, missed the comment on the message

**Comment by talha131** [comment]
Thank you so much for your cooperation.

**Pull request merged**
