### PR TITLE
Separate claims for Google/Bing into includes

### LINKED ISSUE #365: Move claim_google and clam_bing code to separate files
Extract the code into two separate files.

### PR DESCRIPTION
**Pull request by iranzo**
Prerequisites
-------------

- [x] My Pull Request is filled against the `next` branch
- [x] I have updated the [CHANGELOG](https://github.com/Pelican-Elegant/elegant/blob/next/CHANGELOG.md)

Recommended Steps
-----------------

- [ ] My patch adds a new feature, therefore I have also added a help article about it
- [ ] My patch changes Elegant behavior, therefore I have updated the help article to reflect this change
- [x] My commits are [signed](https://help.github.com/en/articles/signing-commits)

Description
-----------

Closes #365 

-----
[View rendered CHANGELOG.md](https://github.com/iranzo/elegant/blob/claimsep/CHANGELOG.md)

### CODE REVIEW

**Comment by iranzo** [comment]
Rebased to avoid conflicts with recent changes, once it's merged I'll cover #364  in another pr

**Comment by talha131** [comment]
This commit should be

```
refactor: move Google and Bing claims to their individual files
```

**Comment by iranzo** [comment]
done thanks!

**Comment by talha131** [comment]
@all-contributors please add @iranzo for infrastructure, tests, code and docs

**Pull request merged**
