### PR TITLE
use DEFAULT_LANG instead of en_US

### PR DESCRIPTION
**Pull request by gshen42**

### CODE REVIEW

**Comment by solbu** [comment]
You fixed the hardcoded en_US, 
but introduces the hardcoding in the templates… Why?

**Comment by GanShen** [comment]
This pull request includes another change, see #153 .

**Comment by solbu** [comment]
Ahh. Now I see it. :-)

**Comment by iranzo** [comment]
@gshen42 Can this be rebased to avoid the conflicts?

**Comment by talha131** [comment]
@iranzo besides rebasing, shouldn't we cherry-pick or request author to open a new PR with just the commit that removes hardcoded `en_us`. Cause for the second commit is for remove `http` from URL, for which we have number of PR already open.

1. https://github.com/Pelican-Elegant/elegant/pull/135/
1. https://github.com/Pelican-Elegant/elegant/pull/167
1. https://github.com/Pelican-Elegant/elegant/pull/131

What do you think?

**Comment by iranzo** [comment]
Yes @talha131 commits/PR should be for only one feature

**Comment by talha131** [comment]
Close via ecc8f0e81b1c96b6025203aa088f7ded36623edc

**Pull request closed without merging**
