### PR TITLE
Define new travis configuration for unified 'doc' and code

### PR DESCRIPTION
**Pull request by iranzo**
-----
[View rendered content/Elegant - Pelican Theme/Elegant-Quickstart.md](https://github.com/iranzo/elegant/blob/newdoc/content/Elegant - Pelican Theme/Elegant-Quickstart.md)

### CODE REVIEW

**Comment by talha131** [comment]
@iranzo is this OR ready? And does it need to be merged into master branch?

**Comment by iranzo** [comment]
Hi, I'm going to make a new change and rebase, and this should be merged on next as well (both branches) we can test first with next and then with master

**Comment by iranzo** [comment]
Uploaded, ready for review :-)

**Comment by iranzo** [comment]
This one needs to get into MASTER and into NEXT

**Comment by talha131** [comment]
Merged via d3ba471930e9626e32c9b7e53fee39c492aef451

**Comment by talha131** [comment]
Thanks a lot @iranzo. Really appreciate your work here

**Comment by iranzo** [comment]
let's double check on results!

**Comment by iranzo** [comment]
Tried pelican-elegant.github.io and seems to work fine and same for /next

**Pull request closed without merging**
