### PR TITLE
Validate commits

### PR DESCRIPTION
**Pull request by iranzo**
This PR does run pelican against the latest 'documentation' content to validate the commit being valid to render the pages

Related with #191

### CODE REVIEW

**Comment by talha131** [comment]
@iranzo now that it is merged, how does it work and which online service does it use?

**Comment by iranzo** [comment]
@talha131 this is using the same thing we do have for documentation, so it is executed via travis-ci.org and does checkout latest 'content' in documentation repo for testing purposes, it uses the committed elegant theme and runs it. (equivalent to make html)

If it executes without errors it returns, will return as 'ok' and will work for each commit/PR

**Comment by iranzo** [comment]
image

From <https://travis-ci.org/dashboard>

**Comment by talha131** [comment]
Does travis uses Pelican 3.* or Pelican 4.*?

Secondly, I noticed there were few warnings in travis, when I generated the documentation, (something about using `{static}` instead of `{filenames}`). Is it possible we get the warnings too in the Travis output on Github?

Like right now, it will either pass or fail. Is it possible that it shows "pass but with warnings".

It's not high priority but would be nice to have.

**Comment by iranzo** [comment]
It does use 4.x as it uses 'pip install pelican' to pull latest

In github, you can see the 'details' of the build but that goes via checking the url link provided, for example:

image

That 'details' goes to <https://travis-ci.org/Pelican-Elegant/elegant/builds/466331980?utm_source=github_status&utm_medium=notification>

And there you can see all the output directly

**Pull request merged**
