### PR TITLE
Nginx 404 fix

### PR DESCRIPTION
**Pull request by alxpettit**
Fix for #276.

### CODE REVIEW

**Comment by silverhook** [comment]
AFAIR, whether the tags, categories and archives have an `.html` extension or not in their URL is a user setting in Pelican.

http://docs.getpelican.com/en/stable/settings.html#url-settings

As long as this fix does not break some other use case, it LGTM as well.

**Comment by talha131** [comment]
I will merge it manually. Nonetheless, question is why we need this patch or the one earlier merged a585719b5a?

> whether the tags, categories and archives have an .html extension or not in their URL is a user setting in Pelican.

If it's a user setting then we don't need a585719b5a either.

**Comment by andrewdstrain** [comment]
> I will merge it manually. Nonetheless, question is why we need this patch or the one earlier merged [a585719](https://github.com/Pelican-Elegant/elegant/commit/a585719b5aac346bc9a5bf1280befadc988a20f2)?
> 
> > whether the tags, categories and archives have an .html extension or not in their URL is a user setting in Pelican.
> 
> If it's a user setting then we don't need [a585719](https://github.com/Pelican-Elegant/elegant/commit/a585719b5aac346bc9a5bf1280befadc988a20f2) either.

By default, Pelican adds .html when generating the files. And the Elegant source code does not follow this default. Just try a `pelican-quickstart` and see. Clearly, you can see the tags.html, categories.html, and archives.html in the output folder - with our without Elegant as a theme. Now look at the Elegant source code and note the `default('tags')`, `default('archives'), 'default('categories') in the code (in master and next branch). The two do not match at all. That is, to get rid of the default .html extension, like coded in Elegant, the user has to change the default pelicanconf.py file.

It may be a user setting but the source code of Elegant should follow the actual Pelican default for when the setting is not in use in the pelicanconf.py file. The Nginx, twisted, Apache 404 error will no longer occur. And, remember, the only reason it does not occur with `pelican -l` is that the webserver adds a .html when the URL is not found.

```
(venv) geek@andy:~/src/GeekingOutWith$ pelican -l
WARNING: Unable to find `/someurl` or variations:
  | /someurl.html
  | /someurl/index.html
  | /someurl/
  | /someurl
```

If it did not do this type of behavior, this 404 error would have popped up from the very beginning.

**Comment by talha131** [comment]
@all-contributors please add @alxpettit for code

**Comment by talha131** [comment]
Close via https://github.com/Pelican-Elegant/elegant/pull/480

**Comment by talha131** [comment]
@andrewdstrain great explanation. Very helpful.

@all-contributors please add @andrewdstrain for code and userTesting

**Pull request closed without merging**
