### PR TITLE
docs(yaspeller): moved one-off spelling and one-article-off spelling …

### PR DESCRIPTION
**Pull request by jackdewinter**
## Prerequisites

- [x] My Pull Request is filled against the `next` branch
- [x] All commits in my Pull Request conform to [Elegant Git commit Guidelines](https://elegant.oncrashreboot.com/git-commit-guidelines)

## Description

Instead of a general addition of any improperly spelled words to the yaspeller.json file, moving words out of that file if:
- the word in question is only used in one file

i.e. by adding everything to the one file just confuses things.

### CODE REVIEW

**Comment by talha131** [comment]
I had a cursory look. You have put a lot of hard work into it.

Do you mind if I review and merge it the coming weekend?

**Comment by jackdewinter** [comment]
Take your time.

**Comment by jackdewinter** [comment]
Any decisions on this?

**Comment by talha131** [comment]
Sorry, Jack. Previously bogged down by the day job and currently sick for a
week. I will review and merge as soon as I recover, hopefully, this weekend.

**Comment by talha131** [comment]
Merged via https://github.com/Pelican-Elegant/elegant/pull/530

**Pull request closed without merging**
