### PR TITLE
Add post_stats support in article.html

### PR DESCRIPTION
**Pull request by azzamsa**
It's look like :

### CODE REVIEW

**Comment by iranzo** [comment]
Lgtm

**Comment by iranzo** [comment]
@azzamsa can you rebase to fix conflicting RELEASE_NOTES? 
Thanks!

**Comment by talha131** [comment]
Wait for the rebase. `next` branch will change. Rebase after 2.1

**Comment by silverhook** [comment]
Closes https://github.com/Pelican-Elegant/elegant/issues/100

Thanks :smile:

**Comment by azzamsa** [comment]
Rebased

**Comment by talha131** [comment]
Close via dfcdf5d

Thank you @azzamsa

**Comment by azzamsa** [comment]
> Thank you @azzamsa

My pleasure.

> Close via dfcdf5d

Would you please tell me how contribution merged in elegant, I don't find any recent commit regarding this pr.

**Comment by talha131** [comment]
@azzamsa I am in the process of preparing 2.0 and 2.1 release. Please wait for the release. Shouldn't take more than an hour now.

**Comment by azzamsa** [comment]
oh great :) cause I don't see any commit in your github tile :)

**Comment by talha131** [comment]
Here you go @azzamsa 

1. 965f4106ee8dcca5fd9de011a48d938c1af45266
1. a638d8913c7716b2823998c6649cdbe793448bdc
1. dfcdf5dcb9dba529b71f833945c07ecade735d6d

**Comment by talha131** [comment]
@all-contributors add @azzamsa for code

**Comment by talha131** [comment]
@all-contributors add @azzamsa for code

**Comment by talha131** [comment]
@all-contributors add @azzamsa for code

**Pull request closed without merging**
