### PR TITLE
Remove hardcoded paths  for archives, tags and categories

### LINKED ISSUE #22: '.html' is hardcoded on Categories, Tags, and Archives
I saw this in `templates/base.html`.

### PR DESCRIPTION
**Pull request by iranzo**
Closes #22

### CODE REVIEW

**Comment by silverhook** [comment]
At a quick glance this looks good to me.

@iranzo, if I understood you correctly, you tested this in your theme as well and it worked?

Did anyone check if it breaks anything for Elegant?

From what I can tell, this is not a feature of Pelican, but would be a new variable within Elegant. If that is the case, we need to add that feature to our [documentation](https://github.com/Pelican-Elegant/documentation) as well.

**Comment by iranzo** [comment]
I was testing more things, but give me 5 mins and you can see it live

**Comment by silverhook** [comment]
I think we would need to include the new variables also in [line 25 of `tipuesearch_set.js`](https://github.com/Pelican-Elegant/elegant/blob/master/static/tipuesearch/tipuesearch_set.js#L25)

Specifically this part:

``` javascript
exclude_pages = ['/archives.html', '/tags.html', '/index.html', '/categories.html', '/search.html'];
```

So search doesn’t break search (once it works again https://github.com/Pelican-Elegant/elegant/issues/147)

**Comment by iranzo** [comment]
I didn't touched that one as I'm not sure if that gets rendered tru jinja or not, let me try

**Comment by iranzo** [comment]
Just tested and the 'rendered' file gets the vars verbatim:

exclude_pages = ['/{{ ARCHIVES_URL }}', '/{{ TAGS_URL }}', '/index.html', '/{{ CATEGORIES_URL }}', '/search.html'];

**Comment by silverhook** [comment]
Hmm, can we parse that through Jinja first, so it creates a new usable `tipuesearch_set.js`?

@talha131, @calfzhou, ideas?

**Comment by talha131** [comment]
To the best of my knowledge, Jinja can't help here. Because tipue search is a static resource. It does not pass through Jinja compiler.

**Comment by silverhook** [comment]
One idea would be to include the most likely options and handle the rest with documentation.

**Comment by iranzo** [comment]
Should we spin another issue for the tipue part and merge the other changes for the issue we can solve now?

**Comment by talha131** [comment]
@iranzo seems so.

1. We merge this commit
1. Create a new a PR for tipue (I think we should add both links in it, with and without html, as a safety measure like `tags.html, tags, archives.html, archives`
1. Add a help article on docs site.

@silverhook what do you think?

**Comment by silverhook** [comment]
> * We merge this commit
> 
> * Create a new a PR for tipue (I think we should add both links in it, with and without html, as a safety measure like `tags.html, tags, archives.html, archives`
> 
> * Add a help article on docs site.

I agree

**Pull request merged**
