### PR TITLE
Upgrade bootstrap version to 3.0.2

### PR DESCRIPTION
**Pull request by calfzhou**
Bootstrap 3 is not backwards compatible with v2.x. So there are several related changes according to the [migration guide](http://getbootstrap.com/getting-started/#migration).

I think it would be better to upgrade bootstrap to v3.x before work on IE issues (#74).

### CODE REVIEW

**Comment by silverhook** [comment]
@talha131 Bump?

**Comment by talha131** [comment]
@silverhook I got your comments on other issues. I will address them all here.

I know an update to Pelican-Elegant is long overdue. Something I hopped to finish in a month is still far from completion after a year.

Elegant-theme was my first introduction to the world of web development and open source projects. Till then I had only worked on desktop apps using mostly C, C++, C# and Objective C. I developed the theme because none of the available theme were exact fit or even close to my vision. 

I didn't know what a templating language like Jinja2 does or what CSS syntax is before I started the project, let alone to know about best framework and practices for CSS. More people than I expected liked the theme, despite my inexperience. But I had shoot myself in the foot at the beginning of development.

# How I got stuck with a wrong framework

I chose Bootstrap2 because I didn't know any better. It was the most popular framework at the time. As it turns out it was a poor choice for the project. 

When they upgraded from Bootstrap2 to Bootstrap3, they made several changes which made backward compatibility impossible. 

They dropped support for Bootstrap2 with the release of version 3. As a result whatever bugs were left in Bootstrap2 flowed down to the theme.

With the upgrade they introduced a flat look, which doubled the work load of upgrading. First you have to make the theme compatible with the Bootstrap3 classes. On top of it you must edit CSS style rules to get the old look back.

Bootstrap is very opinionated. Product splash pages for example, can rock whatever look Bootstrapx introduces. But a blog theme is a different beast. It should not be tightly coupled with the design decisions of Bootstrap developers. In other words, if Bootstrap3 is flat, we shouldn't turn the blog theme to a flat land just for the sake of it.

Believe it or not, I made a conscious decision about every part of the theme. If search box has rounded corner, it wasn't a happenstance. With an upgrade to Bootstrap3, it was necessary to override Bootstrap3 default styles.

At first, I tried to use the only way I was familiar with, using pure CSS. It was a futile exercise. I tried very hard but the changes were just too many. This forced upon me an introduction to Less and SCSS pre processors. I learned that bootstrap custom theme developers tweak the source code of bootstrap. This discovery started another futile effort to learn SCSS, RVM, Ruby gemsets, mixins and what not. 

It didn't work out. The time it was taking to understand the source code and override it was just too much. Meanwhile Bootstrap announced their plans of Bootstrap4. It will be difficult to keep theme in sync with every new version of Bootstrap. I was better off using any other less opinionated framework like Zurb Foundation. 

I dropped all Bootstrap3 update work and started looking for better alternatives. What I learned that my approach was doomed from the start.

If I had any experience in web designing, I would have known that:

All I needed was a simple grid framework. Bootstrap wasn't required at all. All the resources put into upgrading to Bootstrap3 were a waste.

I should have used [PostCSS](https://github.com/postcss/postcss), which has a powerful grid system plugin, [Lost](https://github.com/peterramsing/lost).

Gulp or Grunt makes development much easier. A simple gulp task would have taken care of quite a few things that I used to do manually, like maintaining [coding style](https://github.com/talha131/pelican-elegant/blob/master/CONTRIBUTING.md#follow-the-code-style-of-the-existing-codebase).

If only I had known!

# How I learned the core principle of project management the hard way

Shipping is a feature. Real artists ship. That's the core principle to remember. 

Pelican-Elegant theme was the first project that I managed without any supervision. I made the rookie mistake of vowing to ship a perfect V2.0.

First I kept putting it off till I could update the documentation.

Meanwhile users kept coming up with ideas and reporting bugs. I entertained all of them blithely, thinking more features and less bugs is good for V2.0.

Then the idea to upgrade to Bootstrap3 popped up. There were few bugs in Bootstrap2 that were fixed in Bootstrap3. Feeling bloated with confidence, I made the foolhardy decision of adding "upgrade to Bootstrap3" in V2.0 tasks list. In my defense, I thought it would take only a month at most. 

In hindsight, I should have froze the development and release V2.0, and the continue the development.

I was(am?) stupid. I admit it.

# Then I realized Pelican is not for me

All along I was doing a full time job, studying in a university degree program, and any paid side project that landed on my table. More projects meant more knowledge and experience, which brought a shortcoming of Pelican to my notice.

It is a blog generator and does an excellent job at it. Blog has at most two content types, posts and pages. 

But what if you have to offer more? You want to add your resume to your site. Surely you don't expect theme fit for your blog posts will also fit your resume. You want to add documentation of your side projects, like I did for Elegant. A theme that is designed for posts where you write about your cats, can it also work for project documentation? You want to add a landing page of your project?

An ideal website generator will offer more content types than just pages and posts. Then you can create a theme for every type of content. Imagine if Pelican and Elegant lets you a site where you have,

1. blog posts 
2. your resume
3. your presentations
4. your projects landing page

and each content type gets its own unique theme. Pelican can't but [Hugo](http://gohugo.io/content/types/) can. Hugo is another static blog generator written in Go that has 

> full support for different types of content. A content type can have a unique set of meta data, template 

There is another shortcoming. Say I want to join three different content into one blog post. For example, I have an mp3 file, summary of mp3 file in markdown, transcription of mp3 in a text file, and translation of summary.

I want it appear them in a single post. Audio file on top with three menu items under it. One menu item will show the summary of audio. Clicking on second menu item will switch view to the transcription. Clicking on third will switch to translation.

Can it be done in Pelican? Nope!

Reactjs has introduced several new features that were unimaginable before. For example,

No Page reload transition. See these two example to understand what I am talking about, [demo 1](https://gatsbyjs.github.io/gatsby-starter-blog/) and [demo 2](https://gatsbyjs.github.io/gatsby-starter-documentation/docs/how-to-run/).

Add interactive code demo. See this [example](http://jlongster.com/Removing-User-Interface-Complexity,-or-Why-React-is-Awesome). Scroll down for the demo.

Aren't these nice to have features? That'd need a blog generator written in JavaScript.

# Where do I stand now?

I will not be using Pelican for my site. That's for sure. 

I will use a blog generator that offers different content type and takes advantage of Reactjs. [Gatsby](https://github.com/gatsbyjs/gatsby) looks promising. If it doesn't work out, I would write my own. 

The blog generator I have in mind will,

1. Let user create new content type
2. Offer more taxonomies besides tags and category
3. Let user combine different content files into one post
4. Leverage Reactjs to offer interactive demos and single page app feel to the site

You can see I do not feel very motivated to maintain Pelican theme because of Pelican shortcomings.

# Where does Pelican-Elegant stand?

I think V2.0 is ready as it is, besides whatever bugs are present in Bootstrap2. Run the code from HEAD of master branch to see it in action.

*Option 1* is to copy whatever documentation I have written into the project repository. Release V2.0 from master branch.

A number of users are already running V2.0 from the master branch. I haven't received any complain about it so far.

*Option 2* Write theme from scratch using PostCSS and get rid of Bootstrap crutch for ever. This will not add any new feature or change the look. You will end up with an exact copy of the theme minus Bootstrap2.

Admittedly I don't like option 2 because my heart is set on Reactjs.

Except two or three, most users have not noticed the bugs of Bootstrap2. On the other hand, almost everyone has asked about V2.0.

Option 1 is the shortest path.

Option 2 is long and grunt. I think it should be opted only if Bootstrap2 legacy becomes unbearable or there is a showstopper feature or bug that must be fixed.

I would love to know what users want and expect.

**Comment by silverhook** [comment]
First of all: Wow! Thanks for the immense update. I think this would make a great blogpost.

It took me quite some time to read your update with all the links and everything. My reply won’t be nearly as verbose, but rest assured that quite some thought went into it.

# Code quality, noobie-ness and massive thanks

Don’t sell yourself short. There is a good reason why your theme is quite popular on Pelican.

If you compare that to my [first website][first] – hell, even if you compare it to [the most current page I wrote myself][last] – your first try is in a completely different league.  If that’s really your first take on the web, I’m really impressed! My hat’s off to you, sir :tophat:

Your theme actually saved me from rolling my own, in which case I’d very likely run into the same trap as you did, just not nearly as elegantly tread in and in no way as elegantly get out.

[first]: https://web.archive.org/web/20031217190144/http://lenin.poljane.net/~hook/
[last]: https://dafaq.wheremymonkeyis.at

# Choice of CMS / generator

By reading your reasons, I can understand why Pelican might not be the right choice for you.

For quite the opposite reasons, Pelican is very much is what I need. I mention some of the reasons in this [very lengthy blog post][5th]. The top reason for taking on a static generator for me is that I really to want an as simple as possible and as future proof as possible blog and website. This means that ideally I just want static W3C valid HTML and CSS (with as little JS as possible). I already keep 12 years of my blog posts and don’t want to try to break my skull in a few more years why suddenly my old posts don’t show up as intended.

I imagine others will have similar as well as other reasons why they like Pelican and Elegant.

That being said, this is not to dissuade you from adopting or creating a different blog system. I think the internet is there so everyone can have a homepage and blog they want.

[5th]: http://matija.suklje.name/5th-incarnation-of-hooks-humble-homepage

# Frameworks

OK, as indicated, I am not nearly as good in web development as many others in Elegant are and my skills lie more in FOSS licensing and (community) management.

And in that light, it seems to me that the patent clause in ReactJS’s licence is slightly worrying and personally I’d avoid using it. It is even questionable if it would qualify as a Free Software or Open Source licence. For starters neither FSF nor OSI have approved ReactJS’s licence. The current version is slightly better (i.e. now you don’t lose the patent licence by simply claiming that some FB’s patent is invalid), but still.

As explained above, I would prefer the (future) framework of Elegant to be as lean as possible and to have just as little of it as needed.

From what I heard you, I think moving from Bootstrap to PostCSS seems like a good idea.

# Future plans

IMHO, we should proceed as follow:

 1. add missing documentation
 2. optionally merge HTML5 fix (not because it’s mine, but because it might bring in more interested devs, if Elegant is one of the few themes for Pelican that create 100% valid HMTL5)
 3. release v2
 4. create an new branch or even v3 milestone to migrate to PostCSS
 5. continue normal updates on v2 in parallel to migrating to PostCSS

If I understand you right – and please correct me if and where I’m wrong – you are not planning to actively maintain Elegant for Pelican any more. If that is so, what would your preference be of how the development of Elegant should continue?

Again, thanks for the update and thank you a massive bunch for Elegant!

**Comment by talha131** [comment]
@silverhook Thanks a lot for your encouragement and appreciation. :smile: 

First thing first. I agree that all PR and issues shouldn't be left hanging. They need to be merged. I am on it. That's V2.0.

Now, do we even need a V3? Do we even need to move away from Bootstrap2? They say "If it ain't broke, don't fix it". 

> If I understand you right – and please correct me if and where I’m wrong – you are not planning to actively maintain Elegant for Pelican any more. If that is so, what would your preference be of how the development of Elegant should continue?

I would like stay at the helm. But does Elegant need any more development?

**That's the core question and I would love to get feedback from users.**

Say I,

1. Update documentation
1. Close open issues
1. Merge pull request
1. Update Tipue Search

After it, is there any need of further development?

Kindly share your thoughts on this.

**Comment by silverhook** [comment]
Personally, and here I may be in minority, I would very much like to have a theme that also passes W3C’s CSS tests.

If we want to achieve that it seems the only sane way forward is to get rid of Bootstrap.

I realise I may even be the only one who cares about that, but when I find time I’m willing to work on cleaning that up. Although I’m sure others would be a lot more efficient at this task.

Also there’s the question of support for new plugins and new versions of Pelican.

**Comment by talha131** [comment]
Thank you. 

W3C validation is a low priority. The advantage is just not worth it when compared to the efforts that will go into migrating from Bootstrap2. I am speaking from experience. Of course you are more than welcome to resolve validation issues one by one.

I will go ahead with the plan I mentioned above. ([point 1-4](https://github.com/talha131/pelican-elegant/pull/77#issuecomment-170080087))

**Can you tell me which version of Elegant you are using for your blog? What's the latest commit hash in your Elegant repository?**

**Comment by silverhook** [comment]
Cool, sounds like a plan :)

I’m using [my own fork][fork], which is currently at 32f74bdff2e1fbe62c58eb58e3419096f863c3a7 and as such 18 commits forward from your master.

The last common commit is 44c8fbc (current master of yours)

As for the W3C validation …when/if I find time, I might work on a fork (or branch) to try to get it done. It will probably take me years though :]

[fork]: https://github.com/silverhook/pelican-elegant

**Comment by leotrs** [comment]
What's the stage of this? I am looking forward to using elegant with a newer version of bootstrap.

**Comment by silverhook** [comment]
I haven’t had time to tend to my blog at all recently, so unless someone else worked on getting rid of Bootstrap, the status quo remains the same.

**Comment by silverhook** [comment]
@calfzhou what do you think? Should we simply give up on upgrading to Bootstrap 3.x and scrape all such requests as “wontfix”?

**Comment by calfzhou** [comment]
If we decide not depending on Bootstrap any more, there is no need to fix it.

But i'm not sure about this. Will we move to other framework, or just build what we need by hand?

**Comment by silverhook** [comment]
That is a good question. Personally, I would tend to do it by hand. But it is a hard discussion we should start having, at the latest once 2.0 is out.

**Comment by azzamsa** [comment]
I just migrated to pelican yesterday. I've used Ocotopress for about 2 and half year. Suddenly, I want to integrate my blog writing workflow into Emacs. Turns out I face some difficulties e.g different rake version, octopress still use the old version, and few other. My top reason is Octopress give me bunch of files and directories. I don't even have any clue what those file are doing. Then I decide to move to minimal static generator. I just need simple theme, GA, Disqus. That's all.

Tried jekyll. Indeed I need to be familiar with ruby to customize it. So 'why not python', I have some experience with it. Go to pelican (cause I hear it often, I even didn't know that other python generator exist that time :) ). Then went finding theme that suit with me. Minimal but not too minimal, simple but not to simple. Boom, found site called 'oncrash=reboot', love its theme, and grab **Pelican**.


> An ideal website generator will offer more content types than just pages and posts. Then you can create a theme for every type of content. Imagine if Pelican and Elegant lets you create a site where you have,
> 
>     1. blog posts
> 
>     2. your resume
> 
>     3. your presentations
> 
>     4. your projects landing page
> 
>     5. your podcasts

__I know this is what @talha131 need. But Pelican + Elegant more than enough for my needs__

I just need simple customization: hide specific article that I use as page. So I add two metadata

```
Visible: False
Category: MYPAGE
```

Then hide them in 'achieve', 'tags' and 'categories'

```
{% for article in articles %}
{% if article.visible != 'False' %}
<li itemscope><time itemprop="dateCreated" datetime="{{ article.date.isoformat() }}">{{ article.locale_date }}</time><a href="{{ SITEURL }}/{{ article.url }}">{{ article.title }} {%if article.subtitle %} <small> {{ article.subtitle }} </small> {% endif %} </a></li>
{% endif %}
{% endfor %}            
```

``` html
{% if article.category != 'MYPAGE' %}
{% if loop.last %}
<article itemscope class="last-entry-of-year">
{% else %}
{% set next_year = loop.nextitem.date.strftime('%Y') %}

```

The unsolved problem: how to tell 'neighbor' if article.visible == false. Don't recommend it. And don't category display beside an article if Category == MYPAGE

--------

Or maybe there is trivial solution ?  @talha131  @silverhook , can I put those in /content/pages without adding them to nav-bar ?

I think I will stick to pelican + elegant for now. It more than enough for me. I just need to write, publish it, with no hassle. (and know what x, y file are doing)

Thank you for Elegant. This theme is very awesome!

**Comment by iranzo** [comment]
@calfzhou can this be rebased on top of current master? probably something to deal with after 2.1 is released aligning it with the other releases

**Comment by talha131** [comment]
@iranzo I highly doubt this can be released at all. Bootstrap 3 was not backward compatible with 2 which made upgrade process really tiring. Even the look and feel was different. By 3, it had moved to flat design which was the new flashy thing in those days.

I suggest we close down this issue and get rid of bootstrap completely, as discussed in other threads.

**Pull request closed without merging**
