### PR TITLE
docs(change): fix small typo

### PR DESCRIPTION
**Pull request by silverhook**
## Prerequisites

- [x] My Pull Request is filled against the `next` branch
- [x] All commits in my Pull Request conform to [Elegant Git commit Guidelines](https://elegant.oncrashreboot.com/git-commit-guidelines)

## Recommended Steps

- [ ] My patch adds a new feature, therefore I have also added a help article about it
- [ ] My patch changes Elegant behavior, therefore I have updated the help article to reflect this change
- [ ] My commits are [signed](https://help.github.com/en/articles/signing-commits)

### CODE REVIEW

**Review by iranzo — COMMENTED** [review]
LGTM

**Comment by iranzo** [comment]
@silverhook I've changed it against 'next', can you please rebase to only contain the fix?
Thank you!

**Comment by silverhook** [comment]
> @silverhook I've changed it against 'next', can you please rebase to only contain the fix? Thank you!

I will try. I’m so-so with Git :)

**Comment by iranzo** [comment]
> > @silverhook I've changed it against 'next', can you please rebase to only contain the fix? Thank you!
> 
> I will try. I’m so-so with Git :)

Let me know if you want me to handle it :-)

**Comment by silverhook** [comment]
Closing in favor of https://github.com/Pelican-Elegant/elegant/pull/784

**Pull request closed without merging**
