### PR TITLE
Updated Tipue Search 3.1 => 5.0

### PR DESCRIPTION
**Pull request by 0x8BADFOOD**
Version is too old and does not work properly with latest version of plugin: tipue_search

Please see commit: bb4d5df014f0a6df9b5acd4f40e54f0ce81f4a54

https://github.com/getpelican/pelican-plugins/commit/bb4d5df014f0a6df9b5acd4f40e54f0ce81f4a54

Source of 5.0 version: https://github.com/Tipue/Tipue-Search

### CODE REVIEW

**Comment by silverhook** [comment]
Tipue-Search seems to be 7.0 now, but also has been removed from GitHub, and moved to a zip download from their website: http://www.tipue.com/search/

@0x8BADFOOD, any idea how to move this forward?

**Comment by iranzo** [comment]
We can always use a peru.yaml from <https://github.com/buildinspace/peru> in order to pull/unpack latest version before commiting to master so that it can be done regularly in a more 'automated' way

**Comment by silverhook** [comment]
I’d prefer to keep it simple, but would defer this question to those with more coding mileage than I have.

**Comment by talha131** [comment]
If peru will auto update the external dependency, then it's not a good idea. Updating a dependency should be a conscious effort, lest the update introduces breaking changes and then you are forced to fix them at the eve of new release.

Instead of auto update, it is better if we check the tipue version regularly before making any new release. Also, before upgrading we must think why upgrade. What's the benefit new version is offering. 

After working on few JS projects, I am always wary of upgrading the dependencies unless necessary. The neck break speed at which JS ecosystem runs, does that to you.

**Comment by talha131** [comment]
@iranzo what's your opinion about my feedback on using peru to maintain tipue search always up to date?

**Comment by iranzo** [comment]
Thing is that 'peru' only updates when you run 'peru sync', in the automation setup for both elegant and documentation we do use it for pulling latest plugins, theme, etc

If we want to update the 'static' folder inside elegant still needs someone later adding and submitting PR to get that updated in master.

So peru does automate that part, but still requires review and approval before committing to elegant theme repo, so that address your concerns (AFAIK)

**Comment by talha131** [comment]
Lets leave it then. It's not adding much value here. We do not have lots of dependencies to worry about dependency management.

Later, if we decide to use CSS pre-processors to develop the theme (end user will always get a ready to use CSS), then we may automate updating tipue search step. 

I am also looking into alternative solutions for search. Other popular static blog engines, like Hugo and Gatsby, don't use tipue much (most probably they don't use tipue at all). So lets freeze Peru addtion for now.

**Comment by 0x8BADFOOD** [comment]
> @0x8BADFOOD, any idea how to move this forward?

Sorry for late reply. Now it was merged. Glad that project started to live again :)

**Comment by talha131** [comment]
@all-contributors please add @0x8BADFOOD for code.

**Pull request merged**
