### PR TITLE
Add footnote superscript

### PR DESCRIPTION
**Pull request by seylerius**
In reStructuredText, a class of footnote-reference is applied to footnotes. No reason not to take advantage of that, eh?

### CODE REVIEW

**Comment by silverhook** [comment]
Another question is whether this is reStructuredText-specific or would it work also for MarkDown footnotes.

If it produces a different output depending on which format the author wrote their article, we need to fix it for both input formats.

**Comment by iranzo** [comment]
This should be rebased to also see the issue with the CSS

**Comment by talha131** [comment]
@seylerius Please accept my apologies for getting back to you after 5 long years.

When I use reST footnotes, what I get is



No where do I see `footnote-reference` class. Please let me know a bit more about your reST configuration. 

Output of my `pip freeze` is

```bash
pip freeze
beautifulsoup4==4.7.1
blinker==1.4
cssmin==0.2.0
docutils==0.14
feedgenerator==1.9
invoke==1.2.0
Jinja2==2.10.1
livereload==2.6.1
Markdown==3.1.1
MarkupSafe==1.1.1
pelican==4.0.1
Pygments==2.4.2
python-dateutil==2.8.0
pytz==2019.1
six==1.12.0
smartypants==2.0.1
soupsieve==1.9.2
tornado==6.0.3
typogrify==2.0.7
Unidecode==1.1.1
webassets==0.12.1
```

**Comment by talha131** [comment]
@seylerius I have to close this PR because I can't reproduce the CSS class in reST files.

Once again, please accept my apologies for leaving this PR dormant for so long. I will try to do a better job in future.

**Pull request closed without merging**
