### PR TITLE
Feat applause button

### LINKED ISSUE #532: Add applause button support
https://applause-button.com/

### PR DESCRIPTION
**Pull request by talha131**
Fix #537
Fix #532

### CODE REVIEW

**Comment by azzamsa** [comment]
Thanks a ton for this. Sorry for improper code ( I think I need to learn more about elegant structure .e.g code placement and use of jinja macro)

it works great:

image

Maybe the cause of previous problem is we need [to close the tag](https://github.com/Pelican-Elegant/elegant/pull/540/commits/d37e691e0592bded8dd42531ceacfa61147ad078).

**Comment by talha131** [comment]
> Maybe the cause of previous problem is we need to close the tag.

I think that was because of including CSS incorrectly.

**Comment by azzamsa** [comment]
> I think that was because of including CSS incorrectly.

Oh.

Sorry, I want to ask:

1) instead of merging this PR, why do you still need to open new pr #541 ?
2) how do you move my commit in my previous pr to this pr. using cherry-pick?

**Comment by talha131** [comment]
> instead of merging this PR, why do you still need to open new pr #541 ?

I mistakenly opened it against the master branch. All PR should open against next branch.
Next branch  is merged to master only when releasing a new version.

> how do you move my commit in my previous pr to this pr. using cherry-pick?

Downloaded the patch (just add `.patch` to any PR url) and then applied it.

**Comment by azzamsa** [comment]
> I mistakenly opened it against the master branch. All PR should open against next branch.
> Next branch is merged to master only when releasing a new version.

Oh, I don't spot that. I thought it's a form of 'trick'


> Downloaded the patch (just add `.patch` to any PR url) and then applied it.

Yeah, This my way too. I just ask to gain new knowledge, cause you did it so fast :), I thought there were other tricks.



Thank you.

**Pull request closed without merging**
