### PR TITLE
Add freelists form template

### PR DESCRIPTION
**Pull request by ashwinvis**
Support https://www.freelists.org subscription widget

Docs: https://www.freelists.org/lists/subscription.html

Being used in https://fluiddyn.bitbucket.io

### CODE REVIEW

**Comment by ashwinvis** [comment]
Configuration may look like

```python
FREELISTS_NAME = "fluiddyn"
```

and it also supports the rest of the config variables used in the mailchimp template.

**Comment by talha131** [comment]
Close via 2bbfb0f

**Comment by talha131** [comment]
@all-contributors please add @ashwinvis for code and test

**Comment by ashwinvis** [comment]
Good bot! Thanks @talha131 :tada:

**Comment by talha131** [comment]
@ashwinvis my pleasure. 

You are part of the Elegant team, but I don't have your email address. We sometimes have to communicate with each other via email. Can you please drop me a line at my email `talha131@gmail.com`? Appreciated!

**Pull request closed without merging**
